name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

env:
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/fashionshop?schema=public"

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Lint Backend
        run: npm run lint:api

      - name: Lint Frontend
        run: npm run lint:web

      - name: Typecheck Frontend
        run: npm run typecheck:web

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Run Frontend Tests
        run: npm run test:web

      - name: Run Backend Tests
        run: npm run test:api

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Build Backend
        run: npm run build:api

      - name: Build Frontend
        run: npm run build:web
